version: "3"

services:
    app:
        build:
            context: app
        ports:
            - "5000"
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=flask
    nginx:
        image: nginx:1.23.2
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./static:/static
        depends_on:
            - app
        ports:
            - "80:80"
    postgres:
        build:
            dockerfile: ./Dockerfile.postgres
        hostname: postgres.dev
        depends_on:
            - app
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=flask
